### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by eunicezhou**
put website online
and add readme

### CODE REVIEW

**Comment by cwpeng** [comment]
You should request review explicitly so that I can review for you.

**Comment by eunicezhou** [comment]
紫珍: 已完成3個api和上傳網頁到雲端
公開網址: http://52.198.121.57:3000/ (首頁) 
http://52.198.121.57:3000/api/attractions?page=0 (景點) 
http://52.198.121.57:3000/api/attractions?page=1&keyword=北
http://52.198.121.57:3000/api/mrts (捷運站)

**Comment by cwpeng** [comment]
Follow steps of task 0. Set me as reviewer of your pull request.

**Comment by eunicezhou** [comment]
老師 我是紫珍，我重新設定好您為code reviever了

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. `nextPage` of http://52.198.121.57:3000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD should be 1, `nextPage` of http://52.198.121.57:3000/api/attractions?page=2 should be 3, and so on.
2. Reponse proper error message for http://52.198.121.57:3000/api/attractions?page=5

Fix issues and re-request review.

**Comment by eunicezhou** [comment]
老師 :
我是紫珍，我修改完成了。
測試網址:
公開網址: http://52.198.121.57:3000/ (首頁)
http://52.198.121.57:3000/api/attractions?page=0 (景點)
[http://52.198.121.57:3000/api/attractions?page=1&keyword=北](http://52.198.121.57:3000/api/attractions?page=1&keyword=%E5%8C%97)
http://52.198.121.57:3000/api/mrts (捷運站)

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. All of your attraction data have the same `lat` and `lng` numbers.
2. We just get attractions where keyword is included in attraction name or equals to mrt name, if keyword is available.

Re-request review after you fixed issues.

**Comment by eunicezhou** [comment]
紫珍:
已修改 
1.lat跟lng部分
2.捷運站及景點名稱中含有keyword者

**Review by cwpeng — CHANGES_REQUESTED** [review]
Deploy your new version to EC2 instance so that I can test in the real environment.

**Comment by eunicezhou** [comment]
紫珍:
已完成修改網站，並將其上架到雲端
測試網址:
公開網址: http://52.198.121.57:3000/ (首頁)
http://52.198.121.57:3000/api/attractions?page=0 (景點)
[http://52.198.121.57:3000/api/attractions?page=1&keyword=北](http://52.198.121.57:3000/api/attractions?page=1&keyword=%E5%8C%97)
http://52.198.121.57:3000/api/mrts (捷運站)

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
