### PR TITLE
week3

### PR DESCRIPTION
**Pull request by eunicezhou**
老師:
我是紫珍
這是我stage2 第三周的作業
測試網址:
http://52.198.121.57:3000
http://52.198.121.57:3000/attraction/3

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but your layout exceeds screen width slightly in small to middle size devices.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I see no fix.

**Comment by eunicezhou** [comment]
老師:
我修改好了，再請您幫我看一下

**Review by cwpeng — APPROVED** [review]
1. There are two separating lines.
2. Title and menu in navigator bar should align center vertically.
3. 2 lines of text overlaps with each other in mobile layout.

**Comment by cwpeng** [comment]
Sorry for false approving pull request. Fix issues in comment and re-request review again.

**Comment by cwpeng** [comment]
Reminder, your task has some issues to be fixed, not passed. It's my fault to approve review, but you still have to fix issues and re-request review again.

**Pull request merged**
